sudo: false
language: android
jdk:
  - oraclejdk8
licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
android:
  components:
    # Travis workaround for Android SDK 25 License
    # travis-ci/docs-travis-ci-com#779
    - tools
    - platform-tools
    - tools
    # The BuildTools version used by your project
    - build-tools-26.0.2
    # The SDK version used to compile your project
    - android-25
    # Additional components
    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository
git:
    submodules: false
before_install:
    - pwd
    - ls -a
    - man sed | cat
    - sed -i "" -e "s/git@github.com:/https:\/\/github.com\//" ".gitmodules"
    - git submodule update --init --recursive
script:
    - ./scripts/build.sh
after_success:
    - ./scripts/deliver.sh
