sudo: false
language: android
jdk:
  - oraclejdk8
licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
android:
  components:
    # Travis workaround for Android SDK 25 License
    # travis-ci/docs-travis-ci-com#779
    - tools
    - platform-tools
    - tools
    # The BuildTools version used by your project
    - build-tools-26.0.2
    # The SDK version used to compile your project
    - android-25
    # Additional components
    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository
git:
    submodules: false
before_install:
    # Install git submodules via https
    - sed --in-place -e "s/git@github.com:/https:\/\/github.com\//" ".gitmodules"
    - git submodule update --init --recursive
    # Start the Android emulator https://docs.travis-ci.com/user/languages/android/#How-to-Create-and-Start-an-Emulator
    - echo no | android create avd --force -n test -t android-26 --abi armeabi-v7a
    - emulator -avd test -no-audio -no-window &
    - android-wait-for-emulator
    - adb shell input keyevent 82 &
script:
    - ./scripts/build.sh
after_success:
    - ./scripts/deliver.sh
